server:
  servlet:
    context-path: /ingest
  port: 8090

spring:
  data:
    elasticsearch:
      cluster-name: music_survey
      cluster-nodes: localhost:9200
      repositories: enabled=true
  main:
    allow-bean-definition-overriding: true
  kafka:
    bootstrap-servers: localhost:29092
client:
  music-survey:
    base-url: http://localhost:8070/music-survey
  elasticsearch:
    host: localhost
    port: 9200
app:
  kafka:
    topic: music-survey
    consumer-group: music-survey-group
